homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - python2
  - python3
  - dockutil
  - jq
  - wget
  - gpg
  - pinentry-mac
  - node
  - aws-okta

homebrew_cask_apps:
  - alfred
  - iterm2
  - omnifocus
  - 1password
  - google-chrome
  - 1password-cli
  - bartender
  - toggl
  - docker
  - firefox
  - aws-vault
  - vlc
  - ubersicht
  - dash
  - java
  - vagrant
  - pycharm
  - keybase
  - google-drive-file-stream
  - boxcryptor
  - freedom
  - microsoft-office
  - omnioutliner
  - skype-for-business
  - zoom

mas_installed_apps:
  - { id: 975937182, name: "Fantastical 2" }
  - { id: 441258766, name: "Magnet" }
  - { id: 803453959, name: "Slack" }
  - { id: 1091189122, name: "Bear"}
  - { id: 1094748271, name: "Contacts+" }
  - { id: 572491815, name: "Textastic" }
  - { id: 1369500258, name: "Anesidora" }
  - { id: 777233759, name: "Focus - Time Manager" }
  - { id: 528726140, name: "Mountain" }
  - { id: 1198319098, name: "MarsEdit" }
  - { id: 1055511498, name: "Day One" }

pip_items:
  - virtualenvwrapper

gem_items: []

npm_items:
  - serverless

dockitems_to_remove:
  - Siri
  - Mail
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - Calendar
  - News
  - Google Chrome

dockitems_to_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Safari
    path: /Applications/Safari.app
    pos: 2
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 3
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 4
  - name: Fantastical 2
    path: "/Applications/Fantastical 2.app"
    pos: 5
  - name: Messages
    path: /Applications/Messages.app
    pos: 6
  - name: iTunes
    path: /Applications/iTunes.app
    pos: 7
  - name: App Store
    path: "/Applications/App Store.app"
    pos: 8
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 9

wallpaper_file: janky.jpg
