homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - python2
  - python3
  - dockutil
  - tmux
  - jq
  - wget

homebrew_cask_apps:
  - alfred
  - iterm2
  - chrome
  - spark
  - omnifocus
  - fantastical

pip_items:
  - virtualenvwrapper

gem_items:
  - tmuxinator

dockitems_to_remove:
  - Siri
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - Calendar

dockitems_to_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: Spark
    path: "/Applications/Spark.app"
    pos: 3
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 4
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 5
  - name: Fantastical 2
    path: "/Applications/Fantastical 2.app"
    pos: 6
  - name: Messages
    path: /Applications/Messages.app
    pos: 7
  - name: iTunes
    path: /Applications/iTunes.app
    pos: 8
  - name: App Store
    path: "/Applications/App Store.app"
    pos: 9
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 10