homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - python2
  - python3
  - dockutil
  - jq
  - wget
  - gpg
  - pinentry-mac
  - node

homebrew_cask_apps:
  - alfred
  - iterm2
  - omnifocus
  - 1password

mas_installed_apps:
  - { id: 975937182, name: "Fantastical 2" }
  - { id: 441258766, name: "Magnet" }

pip_items:
  - virtualenvwrapper

gem_items: []

npm_items:
  - serverless

dockitems_to_remove:
  - Siri
  - Mail
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - Calendar
  - News
  - Google Chrome

dockitems_to_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Safari
    path: /Applications/Safari.app
    pos: 2
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 3
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 4
  - name: Fantastical 2
    path: "/Applications/Fantastical 2.app"
    pos: 5
  - name: Messages
    path: /Applications/Messages.app
    pos: 6
  - name: iTunes
    path: /Applications/iTunes.app
    pos: 7
  - name: App Store
    path: "/Applications/App Store.app"
    pos: 8
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 9

wallpaper_file: blue_chick.jpg
