homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - versent/homebrew-taps
  - aws/tap
  - hashicorp/tap

homebrew_installed_packages:
  - python3
  - dockutil
  - gpg
  - pinentry-mac
  - tmux
  - saml2aws
  - mosh
  - awscli
  - wget
  - jq
  - tflint
  - vault
  - packer
  - tfenv
  - terraform-docs
  - pre-commit
  - gawk
  - cfn-lint
  - aws-sam-cli
  - ffmpeg
  - mp4v2
  - mp3val
  - mp3splt
  - rbenv
  - openjdk
  - gimme-aws-creds
  - node
  - go
  - aws-iam-authenticator
  - groovy


homebrew_cask_apps:
  - alfred
  - iterm2
  - 1password
  - omnifocus
  - dropbox
  - boxcryptor
  - bartender
  - 1password-cli
  - microsoft-office
  - freedom
  - textexpander
  - keyboard-maestro
  - toggl-track
  - vlc
  - logos
  - dash
  - vmware-fusion
  - devonthink
  - zoom
  - calibre
  - google-chrome
  - firefox
  - protonmail-bridge
  - intellij-idea
  - expressvpn
  - docker
  - numi
  - elgato-stream-deck
  - logitech-options
  - logitech-g-hub
  - keybase
  - send-to-kindle
  - omnioutliner
  - ringcentral
  - sf-symbols
  - scrivener
  - datagrip
  - podcastmenu

homebrew_cask_uninstalled_apps:
  - launchbar

mas_installed_apps:
  - { id: 441258766, name: "Magnet" }
  - { id: 975937182, name: "Fantastical 2" }
  - { id: 803453959, name: "Slack" }
  - { id: 777233759, name: "Focus - Time Manager" }
  - { id: 1295203466, name: "Remote Desktop 10" }
  - { id: 1094748271, name: "Contacts+" }
  - { id: 1387167765, name: "Diarly" }
  - { id: 1435957248, name: "Drafts" }
  - { id: 1514795049, name: "OmSavee" }
  - { id: 1439967473, name: "Okta Extension" }
  - { id: 1529448980, name: "Reeder 5" }
  - { id: 967805235, name: "Paste - Clipboard Manager" }
  - { id: 1055511498, name: "Day One" }  
  - { id: 451907568, name: "Paprika Recipe Manager" }
  - { id: 407963104, name: "Pixelmator" }
  - { id: 905384638, name: "Filebot" }
  - { id: 405399194, name: "Kindle" }
  - { id: 572491815, name: "Textastic" }
  - { id: 1444383602, name: "GoodNotes" }
  - { id: 1437130425, name: "Jolt of Caffeine" }
  - { id: 1035237815, name: "Commander One Pro" }
  - { id: 429449079, name: "Patterns" }
  - { id: 890031187, name: "Marked 2" }
  - { id: 1354318707, name: "Core Tunnel" }
  - { id: 1290358394, name: "Cardhop" }
  - { id: 1481302432, name: "Instapaper Save" }
  - { id: 497799835, name: "Xcode" }


pip_items:
  - virtualenvwrapper

gem_items: []

npm_items: []
  

dockitems_to_remove:
  - Siri
  - Mail
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - Calendar
  - News
  - Podcasts
  - TV
  - Safari

dockitems_to_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Safari
    path: /Applications/Safari.app
    pos: 2
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 3
  - name: Drafts
    path: "/Applications/Drafts.app"
    pos: 4
  - name: DEVONthink 3
    path: "/Applications/DEVONthink 3.app"
    pos: 5
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 6
  - name: Messages
    path: "/System/Applications/Messages.app"
    pos: 7
  - name: Music
    path: /System/Applications/Music.app
    pos: 8
  - name: App Store
    path: "/Applications/App Store.app"
    pos: 9
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 10

